# Site Settings
title: Welcome to Jacob's dev World!
email: holypoll@naver.com
description: hello.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jacob-dev.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Jacob Hwang 
user_description: 웹기반 기술에 관심이 많은 개발자 입니다.
disqus_username: jacob-dev

# Social Media
# Remove the item if you don't need it
github_username: hwangtan
facebook_username: holypoll
linkedin_username: hwangtan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
